-- Nuevos medios de pago: WebPay y Mercado Pago
ALTER TYPE "MedioPago" ADD VALUE IF NOT EXISTS 'WEBPAY';
ALTER TYPE "MedioPago" ADD VALUE IF NOT EXISTS 'MERCADOPAGO_LINK';
ALTER TYPE "MedioPago" ADD VALUE IF NOT EXISTS 'MERCADOPAGO_TARJETA';
